# Generated by Django 3.2 on 2023-08-02 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="title",
            name="name_year_unique_relationships",
        ),
    ]
