# Generated by Django 3.2 on 2023-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
