# Generated by Django 3.2 on 2023-08-02 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_auto_20230803_0150"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titlegenre",
            options={"ordering": ("id",)},
        ),
    ]
