# Generated by Django 3.2 on 2023-08-02 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_alter_titlegenre_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titlegenre",
            options={},
        ),
    ]
