# Generated by Django 3.2 on 2023-07-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2023-07-26T03:36:41.121573Z', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
